### ISSUE TITLE
Chart claims v2.6.2 but image is still tagged 2.6.1

### ISSUE THREAD

**Issue by marcoceppi** [bootc/netbox-chart#1]
I found this repository originally on git.boo.tc but couldn't open an account there - I'm glad it's mirrored here.

The Chart metadata claims v2.6.2 but the tag in the values.yaml hasn't been updated yet.

**Comment by bootc** [comment]
I'm really sorry, GitHub has been failing to notify me of issues and PRs on my own repo so I've only just seen this. Thanks for your contribution! It might take me a few days to get enough time to review everything and react to things, but I'll get to it all ASAP.

**Comment by marcoceppi** [comment]
This PR is ancient, since you've been keeping up with netbox in general. We use this chart internally so I'm keen to helping whenever via PRs
