### ISSUE TITLE
Update Redis to >=15.6.10

### ISSUE THREAD

**Issue by norman-zon** [bootc/netbox-chart#103]
I experience an issue with Redis, that has been [discussed and resolved](https://github.com/bitnami/charts/issues/9075) in the Redis Issues, but has been released `15.6.10`. Can you please update the subchart version?

**Comment by bootc** [comment]
Yes, this will be part of the upcoming release which I now plan to complete in the next couple of days.

**Comment by bootc** [comment]
This is included in chart version 4.1.0.
