### ISSUE TITLE
Add DB_WAIT_DEBUG when debug is enabled

### ISSUE THREAD

**Issue by abhi1693** [bootc/netbox-chart#107]
Although `debug` should never be set to `true` in production, however, for testing deployments, it would be super handy if I set `debug: true`, it automatically sets the `DB_WAIT_DEBUG=1` in the env and removes it when I disable debug

**Comment by abhi1693** [comment]
Unfortunately, I won't have time to make the change. I'm not yet that good with helm templates yet.

**Comment by bootc** [comment]
This is fixed in https://github.com/bootc/netbox-chart/commit/9b1eb184ad3e4ea85041d19ab9a073152d7443b1.

**Comment by bootc** [comment]
This is included in chart version 4.1.0.
