### ISSUE TITLE
Additional SSO resources

### ISSUE THREAD

**Issue by tobikris** [bootc/netbox-chart#110]
I love the addition of SSO. The small paragraph about the configuration (https://github.com/bootc/netbox-chart#configuring-sso) is pretty short though and misses out on role and permissions. With some fiddling I have both GitLab and Keycloak working as identity providers and would like to document the configuration somewhere. The current README is probably not the best place though, so for now it is in a gist: [SSO with GitLab](https://gist.github.com/tobikris/462697db32d43714a144fa922850911d#file-with-sso-gitlab-yaml) & [SSO with Keycloak](https://gist.github.com/tobikris/462697db32d43714a144fa922850911d#file-with-sso-keycloak-yaml).

(I was inspired by https://gist.github.com/nahun/5d4d715ca37a2465aaf59ab152413dc2#file-custom_pipeline-py)

**Comment by bootc** [comment]
It sounds like it might be handy to have a `doc` directory which contains more in-depth documentation and/or examples like these. Would you be happy to submit a PR to include the contents of your Gists in the repository?

**Comment by tobikris** [comment]
Yes, I would definitely like to do this. I will open a PR with the beginning of a docs directory.

**Comment by tad-david** [comment]
Thanks for these examples, very helpful! I had some problems getting it to work using secrets from the Keycloak example, it did work using env variables but not secret. Had to update from this:
```
extraConfig:
  - secret:
    secretName: keycloak-client
```
To this:
```
extraConfig:
  - secret:
      secretName: keycloak-client
      items:
        - key: oidc-keycloak.yaml
          path: oidc-keycloak.yaml
      optional: false
```
Also could it also be an idea to specify that `      client_id = '<OAUTH_CLIENT_ID>'` in `sso_pipeline_roles.py` should be replaced in the top? Easy to forget unless reading through the code :)

**Comment by tobikris** [comment]
Thanks for your input. The first one got incorrectly indented - maybe this was your issue?
I added some words about the client ID, good point.
