### ISSUE TITLE
Update netbox to 3.3.6

### ISSUE THREAD

**Issue by felixhuettner** [bootc/netbox-chart#120]
The netbox 3.3.6 release contains the fix for the latest openssl vulnerability.
It would be great if we could get the version also in this chart

https://github.com/netbox-community/netbox-docker/issues/874

Thanks very much

**Comment by redzioch** [comment]
Just add to values: `--set="image.tag-v3.3"` to have version updated to newest from 3.3 line. You can also pin to specific version - just pick desired one from https://hub.docker.com/r/netboxcommunity/netbox/tags

**Comment by felixhuettner** [comment]
Yep we already do that.
However since the last commit (https://github.com/bootc/netbox-chart/commit/dde8cfd498373499bb4970567904129a0202c397) was also a netbox version bump i thought i'll just let everyone here know that it might be necessary to do this again

**Comment by felixhuettner** [comment]
Thank you
