### ISSUE TITLE
redis | Unable to connect to MASTER: Invalid argument

### ISSUE THREAD

**Issue by jadsy2107** [bootc/netbox-chart#124]
Installed like this: 

```bash
helm install netbox bootc/netbox -n netbox --create-namespace --set loginRequired=true
```

Error redis headless 

![Screen Shot 2022-11-28 at 12 11 05 pm](https://user-images.githubusercontent.com/107200645/204171432-f46b6ab7-221f-4c4c-9a4a-b5bf856de4b3.png)

![Screen Shot 2022-11-28 at 12 11 40 pm](https://user-images.githubusercontent.com/107200645/204171494-c90a5283-401c-4bd2-9ec3-c74f1c023db9.png)

**Comment by jadsy2107** [comment]
Well that was an easy fix;

values.yaml

```yaml
redis:
  enabled: true
  clusterDomain: kube.local
````

@bootc 
Maybe add to your values.yaml ?

**Comment by bootc** [comment]
This is a configuration setting in the Redis sub-chart. We can't copy all of the sub-charts' docs and value into this chart or it would drown out anything related to NetBox.

**Comment by jadsy2107** [comment]
OK.. fair - great chart ! Thank you
