### ISSUE TITLE
Error on postgresql service port 'nil pointer evaluating interface {}.port'

### ISSUE THREAD

**Issue by rcalma** [bootc/netbox-chart#131]
`Error: template: netbox/templates/worker-deployment.yaml:29:28: executing "netbox/templates/worker-deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: netbox/templates/configmap.yaml:76:22: executing "netbox/templates/configmap.yaml" at <.Values.postgresql.service.port>: nil pointer evaluating interface {}.port`

The above error appears upon doing helm install after moving it to the local repo.

Changes on my end:
on serviceaccount.yaml added the line:
`automountServiceAccountToken: false`
This ^ was needed to follow the security requirements inside our company.
The chart was then repackaged and uploaded to our local repository via the ff commands:
`helm dependency update charts/${NETBOX_CHART_NAME}`
`helm package charts/${NETBOX_CHART_NAME}`
`CHART="${NETBOX_CHART_NAME}-${NETBOX_HELM_VERSION}.tgz"`
`curl --user ${{ env.ARTIFACTORY_USER }}:${{ env.ARTIFACTORY_API_KEY }} --data-binary @${CHART} -X PUT "${HELM_REPOSITORY}/${NETBOX_CHART_NAME}/${CHART}`

if it helps, all of these was done via github actions.

Can anyone shed some light here please?

**Comment by rcalma** [comment]
For anyone who will stumble on this same issue.
You can avoid this issue if you stop using the built-in dependencies.
Try installing or using external Databases like bitnami/redis and bitnami/postgresql

**Comment by bootc** [comment]
Yep, this is due to changes with the upstream Bitnami PostgreSQL chart. The next release will update the bundled chart, making all the required changes in the chart, and will also ship a `Chart.lock` file to ensure that the version of the bundled chart always matches the expected version.

**Comment by hanbinloop** [comment]
> Yep, this is due to changes with the upstream Bitnami PostgreSQL chart. The next release will update the bundled chart, making all the required changes in the chart, and will also ship a `Chart.lock` file to ensure that the version of the bundled chart always matches the expected version.

i need new version

**Comment by rjhenry** [comment]
You can always manage the PostgreSQL chart yourself, as is recommended in [the README](https://github.com/bootc/netbox-chart#production-usage)
