### ISSUE TITLE
Unable to reach Netbox pod/app gui deployed in Kubernetes cluster 

### ISSUE THREAD

**Issue by Eoj47** [bootc/netbox-chart#132]
Can anyone help with this?

My team and I got our pod running fine but we are unable to reach the app gui. Below is the output of the curl command. 

NOTE - we had to set the readiness probe to false to allow the deployment to run through.. Had a prior issue with readiness probe  "connection was refused" error we could not resolve. Afterwards, the curl begins but does not follow through to completion. 

curl -l https//“domain name”.com -vvL

*   Trying 10.98.206.168:443...
* Connected to “domain name”.com (10.98.206.168) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=* “domain name”.com
*  start date: Nov  2 00:00:00 2022 GMT
*  expire date: Dec  2 23:59:59 2023 GMT
*  subjectAltName: host ”domain name”.com" matched cert's "*. “domain name"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: “domain name”.com
> User-Agent: curl/7.85.0
> Accept: */*
>

**Comment by bootc** [comment]
What do the logs in your netbox pod(s) say?

**Comment by Eoj47** [comment]
🧬 loaded config '/etc/netbox/config/configuration.py'
26
🧬 loaded config '/etc/netbox/config/extra.py'
25
🧬 loaded config '/etc/netbox/config/logging.py'
24
🧬 loaded config '/etc/netbox/config/plugins.py'
23
💡 Superuser Username: admin, E-Mail: admin@example.com
22
↩️ Skipping startup scripts
21
✅ Initialisation is done.
20
⏳ Waiting for control socket to be created... (1/10)
19
2023/01/12 22:16:17 [warn] 7#7 Unit is running unprivileged, then it cannot use arbitrary user and group.
18
2023/01/12 22:16:17 [info] 7#7 unit 1.27.0 started
17
2023/01/12 22:16:17 [info] 16#16 discovery started
16
2023/01/12 22:16:17 [notice] 16#16 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
15
2023/01/12 22:16:17 [info] 7#7 controller started
14
2023/01/12 22:16:17 [notice] 7#7 process 16 exited with code 0
13
2023/01/12 22:16:17 [info] 18#18 router started
12
2023/01/12 22:16:17 [info] 18#18 OpenSSL 3.0.2 15 Mar 2022, 30000020
11
⚙️ Applying configuration from /etc/unit/nginx-unit.json
10
2023/01/12 22:16:18 [info] 22#22 "netbox" prototype started
9
2023/01/12 22:16:18 [info] 23#23 "netbox" application started
8
✅ Unit configuration loaded successfully
7
2023/01/12 22:16:20 [notice] 7#7 process 14 exited with code 0
6
2023/01/12 22:16:20 [info] 60#60 "netbox" application started
5
10.98.67.54 - - [12/Jan/2023:22:16:20 +0000] "GET / HTTP/1.1" 302 0 "-" "curl/7.79.1"
4
2023/01/12 22:16:32 [info] 61#61 "netbox" application started
3
10.98.201.227 - - [12/Jan/2023:22:16:32 +0000] "GET / HTTP/1.1" 302 0 "-" "curl/7.85.0"
2
2023/01/12 22:18:43 [info] 62#62 "netbox" application started
1
10.98.67.54 - - [12/Jan/2023:22:18:43 +0000] "GET / HTTP/1.1" 302 0 "-" "curl/7.85.0"

**Comment by Eoj47** [comment]
See logs above, obtained from ArgoCD

**Comment by bootc** [comment]
Well it looks like it started fine there. I suspect the issue will be with your Ingress controller or Ingress configuration. Could you include your `values.yaml` or your changes to the chart values that you used, please?

**Comment by dmaclaury** [comment]
I've attached what we're using for values.yaml. We re-deployed everything including the RDS database and Elasticache for redis and did confirm that the postgresql DB is being queried successfully on first start to setup schema, etc.

[values.clean.txt](https://github.com/bootc/netbox-chart/files/10438184/values.clean.txt)

We're using an external secret and used `bin/bash` inside the pod to confirm that all the values were being passed in correctly. These 3 values are empty strings, which from our understanding of the README is ok, since we do not need the features at this time:
- `napalm_password`
- `ldap_bind_password`
- `email_password`

**Comment by bootc** [comment]
@dmaclaury is this the same instance of NetBox as the issue reported by @Eoj47? Just checking before this issue veers off, talking about a potentially different problem altogether.

**Comment by dmaclaury** [comment]
Yes, it is the same instance as @Eoj47.

**Comment by dmaclaury** [comment]
@bootc we figured this out. Our Elasticache Redis DB had SSL enabled, and we missed enabling that on our chart.

Thank you for looking this over.

**Comment by bootc** [comment]
Ah that explains it, glad you got it sorted.
