### ISSUE TITLE
Need a way to override NGINX Unit configuration

### ISSUE THREAD

**Issue by vintury** [bootc/netbox-chart#134]
Chart version 4.1.1
netbox version 3.4.2

Params:
`preferIPv4: true`

Error:
```
⚙️ Applying configuration from /etc/unit/nginx-unit.json
2023/01/17 14:03:53 [alert] 7#7 socket(\"[::]:8080\") failed (97: Address family not supported by protocol)
2023/01/17 14:03:53 [alert] 18#18 failed to apply new conf
⚠️ Could no load Unit configuration
2023/01/17 14:03:53 [notice] 7#7 process 14 exited with code 1
2023/01/17 14:03:53 [notice] 7#7 process 17 exited with code 0
2023/01/17 14:03:53 [notice] 7#7 process 18 exited with code 0
```

**Comment by pagey101** [comment]
Was just browsing and saw this, you need to remove the NGINX ipv6 config (hard coded in the image):
https://github.com/netbox-community/netbox-docker/wiki/Troubleshooting#netbox-container-doesnt-start-when-ipv6-is-disabled

**Comment by bootc** [comment]
I'm using NetBox 3.4.x with no issues. By the sounds of things it's exactly what @pagey101 says. The chart should probably have a mechanism to overrside the `nginx-unit.json` configuration for such cases.

**Comment by patrickfnielsen** [comment]
I would be happy to add the this feature as I also have the need. Let me know if a PR is accepted for this

**Comment by papanito** [comment]
You can add the config in a config map and then do this in the helm-values

```
    extraVolumeMounts:
      - name: nginx-config
        mountPath: /etc/unit/nginx-unit.json
        subPath: nginx-unit.json

    extraVolumes:
      - name: nginx-config
        configMap:
          name: nginx-config
```

**Comment by bootc** [comment]
I've added this in 7bd55521ddcc9c99ce710479892f321c2e5226d7 and it will be in the next release of the chart.

**Comment by rossigee** [comment]
I could really use this fix.

When will the next release of the chart be?

(The last one was over a year ago - Aug 15, 2022!)
