### ISSUE TITLE
Recommended way to install plugins

### ISSUE THREAD

**Issue by redzioch** [bootc/netbox-chart#135]
Is there any recommended way to install plugins?

Browsing through docs I found values for plugin config, but I understand, that I still need to deploy plugin code itself.

Should I create custom docker image like documented in Netbox docs or maybe there is better way? https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins#custom-docker-file

**Comment by remram44** [comment]
That's the way I use, instructions for the Docker image apply to Helm.

**Comment by bootc** [comment]
The recommended way to deploy plugins in NetBox with this Helm chart, and with the upstream Docker image that it uses, is to build your own image that includes the plugin(s) and all their dependencies.

**Comment by ybizeul** [comment]
Sorry for reviving an old issue, what about having a way to do it in a unit container ? Maybe already possible ?

**Comment by remram44** [comment]
That's not the container way. Code should be in the image.
