### ISSUE TITLE
Is the serviceAccountToken needed in the pods?

### ISSUE THREAD

**Issue by joachimBurket** [bootc/netbox-chart#143]
Is the serviceAccountToken needed in Netbox pods? We have a security policy in our cluster that prevents deploying when `automountServiceAccountToken` is not set to `false`. So if it is not used in  the pods, it would be great to set it `automountServiceAccountToken` of the pods to `false`. 

This would also enhance the security (see https://hub.armosec.io/docs/c-0190).

**Comment by bootc** [comment]
I don't think NetBox does anything with the Kubernetes API at all, so it should be safe to not auto-mount the service account token. Would you be happy to submit a PR that turns it off by default, but still allows enabling it in case someone needs it?

**Comment by joachimBurket** [comment]
Would you prefer that I add a value so that someone can enable it, or to add documentation on how to manually mount the token?
