### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by D3luxee** [bootc/netbox-chart#149]
Hi,
usually i do not ask for something like this but i would love to have netbox 3.4.4 and it was already added to the chart.
Now its 3 months and i would humbly ask if anything is blocking a new helm release?

Is there a regular release cycle you follow that i'm not aware of?

We are very thankful for this chart, keep up the good work!

**Comment by lion7** [comment]
I was trying to figure out why setting `logoutRedirectUrl: ...` in my chart didn't do anything, but it seems that setting was added in one of the latest (not-yet released) commits.

@bootc any chance to get a new release soon? 😄

**Comment by Arturx47** [comment]
also following this :)

**Comment by chuegel** [comment]
me too ;)

**Comment by lion7** [comment]
@bootc ping so maybe this gets your attention 🙈

**Comment by bootc** [comment]
I'm actively working on finishing up my changes and pushing a new version soon. Please see #162 and #164.

**Comment by Atoms** [comment]
can chart be released proper way: https://charts.boo.tc/charts/ i don't see 5.0.0 version there or https://artifacthub.io/packages/helm/bootc/netbox

**Comment by D3luxee** [comment]
@bootc did you manage to create a release?

**Comment by nowakmax** [comment]
@bootc any chances to new release ?
