### ISSUE TITLE
Deprecated PostgreSQL Chart 

### ISSUE THREAD

**Issue by alex1989hu** [bootc/netbox-chart#15]
**ISSUE:**
netbox-chart depends on [deprecated](https://github.com/helm/charts/pull/21408) PostgreSQL Chart 
https://github.com/bootc/netbox-chart/blob/02bd748341393eb0425ade22ced3f87992cbd120/requirements.yaml#L2-L5

**Comment by bootc** [comment]
This is fixed in chart version `2.1.0`, which includes NetBox 2.8.1 (but can support NetBox 2.7.11 or above).
