### ISSUE TITLE
Ability to add imagePullSecrets to ServiceAccount

### ISSUE THREAD

**Issue by rossigee** [bootc/netbox-chart#152]
We pull our images to a local container registry and scan them before deploying them. Our local container registry uses authentication. We add the auth details to the service account for each application, but there's no option for this in the current `ServiceAccount` template.

**Comment by rossigee** [comment]
https://github.com/bootc/netbox-chart/pull/153

**Comment by rossigee** [comment]
Btw, I tried using the existing 'imagePullSecrets' chart value but it fails the Helm release for some reason...

```
json: cannot unmarshal string into Go struct field PodSpec.spec.jobTemplate.spec.template.spec.imagePullSecrets of type v1.LocalObjectReference
```

Although the YAML it generates looks OK to me. :shrug:

**Comment by bootc** [comment]
> Btw, I tried using the existing 'imagePullSecrets' chart value but it fails the Helm release for some reason...
> 
> ```
> json: cannot unmarshal string into Go struct field PodSpec.spec.jobTemplate.spec.template.spec.imagePullSecrets of type v1.LocalObjectReference
> ```
> 
> Although the YAML it generates looks OK to me. 🤷

The field is a list of references to secrets. If you had a Secret called `my-pull-secret` your field should look like:

```yaml
imagePullSecrets:
- name: my-pull-secret
```
