### ISSUE TITLE
Integrate Okta with NetBox using socialAuth

### ISSUE THREAD

**Issue by Conacious** [bootc/netbox-chart#156]
Hi guys, 
I'm trying to integrate Okta with NetBox using the social-auth python library.

I followed python-social-auth docs https://python-social-auth.readthedocs.io/en/latest/backends/okta.html and
NetBox docs to configure it https://github.com/bootc/netbox-chart/blob/develop/docs/auth.md

After setting everything I can see the login button when I access NetBox:
![image](https://github.com/bootc/netbox-chart/assets/37004512/19c46729-4ea6-4ff4-9fa5-586729caed13)

However, when I click I get the following error:

![image](https://github.com/bootc/netbox-chart/assets/37004512/7364782c-3a42-4a08-9322-24195487b0e1)

Does anyone know how to modify the django.urls using the helm chart? Maybe I'm missing something but I'm a bit stuck in this step.

Thank you guys.

**Comment by imdhruva** [comment]
got a similar error; this is mostly due to bad okta client id or auth server being set. refer: https://developer.okta.com/docs/concepts/auth-servers/#org-authorization-server

**Comment by bootc** [comment]
I don't think there's a way of influencing the `django.urls` / `urlpatterns` through the configuration. The `social_django` should be setting up the URLs correctly to point back at itself; if it's not I'd go asking for help from the NetBox and/or Python Social Auth projects.
