### ISSUE TITLE
Error while using bundled postgresql database

### ISSUE THREAD

**Issue by Analepse129** [bootc/netbox-chart#168]
Hello,
I'm encountering strange behavior while trying to launch this helmchart through an argocd applicationset with the bundled postgresql.
I'm using the 4.1.1 tag version.

Here's my config in the applicationset.yaml file :
```
 sources:
    - repoURL: https://charts.boo.tc
      chart: netbox
      targetRevision: 4.1.1
      helm:
         valuesObject:
           postgresql:
              enabled: true
              postgresqlUsername: netbox
              postgresqlDatabase: netbox
              postgresqlPassword: netbox
              postgresqlPostgresPassword: netbox
```
> Note that I adapted the TL;DR section of the readme to yaml style. Maybe this is the issue ?
> ```--set postgresql.postgresqlPostgresPassword=[password1]```
> ```--set postgresql.postgresqlPassword=[password2]```

And here's my output at deployment :

Bundled postgresql :
```
postgresql 14:04:54.58 INFO  ==> ** PostgreSQL setup finished! **
postgresql 14:04:54.60 INFO  ==> ** Starting PostgreSQL **
2023-11-07 14:04:54.631 GMT [1] LOG:  pgaudit extension initialized
2023-11-07 14:04:54.632 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-11-07 14:04:54.632 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2023-11-07 14:04:54.635 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-11-07 14:04:54.650 GMT [92] LOG:  database system was shut down at 2023-11-07 14:04:42 GMT
2023-11-07 14:04:54.662 GMT [1] LOG:  database system is ready to accept connections
2023-11-07 14:05:05.884 GMT [105] FATAL:  password authentication failed for user "netbox"
2023-11-07 14:05:05.884 GMT [105] DETAIL:  Password does not match for user "netbox".
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```
Netbox :
```
⏳ Waiting on DB... (24s / 30s)
django.db.utils.OperationalError: connection to server at "netbox-postgresql" (172.20.15.184), port 5432 failed: FATAL:  password authentication failed for user "netbox"
[ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
⏳ Waiting on DB... (27s / 30s)
❌ Waited 30s or more for the DB to become ready.
```

It's weird, because it seems that the postgresql doesn't create the couple user/pswd I'm asking it to create.
In any case you already have encountered this error somewhere... 
Thanks for your answers ! :)

**Comment by bootc** [comment]
I'm not familiar with ArgoCD myself but your YAML snippet doesn't look incorrect to me. I think the most likely thing is you've tried to deploy this a couple of times, and didn't have the password for PostgreSQL configured correctly the first time around. When the Bitnami PostgreSQL instance first launches, Kubernetes creates its storage volume (the PVC) and the PostgreSQL container initialises the database with the password it had at the time. If that password changes on subsequent runs and you don't delete the PVC beforehand, it makes no attempt to update the password in the database on the storage, leading to such errors.

You probably need to:
1. Un-deploy the chart altogether
2. Delete the PVC that will be left behind
3. Deploy again using the appropriate options

You should, however, review the [Production Usage](https://github.com/bootc/netbox-chart/tree/develop#production-usage) section of the README, as I would strongly encourage you to deploy PostgreSQL and Redis separately from the NetBox chart.

**Comment by Analepse129** [comment]
Thanks for you answer ! You guessed it well, that's exactly what I did. 
After applying your recommandations, it works flawlessly.
I'll consider updating my configuration tu run an external database.
