### ISSUE TITLE
Cognito SSO integration issue

### ISSUE THREAD

**Issue by Analepse129** [bootc/netbox-chart#169]
Hello,

I can't figure out how to make this helmchart work with the aws cognito SSO. I followed both the example availiable on the repo and the one at this webpage : https://python-social-auth.readthedocs.io/en/latest/backends/cognito.html

I added this block of code at the end of my working applicationset :
```
 # ADDED SECTION FOR SSO
              remoteAuth:
                enabled: true
                backends:
                  - social_core.backends.cognito.CognitoOAuth2
                header: HTTP_REMOTE_USER
                autoCreateUser: true

              extraConfig:
                - secret:
                    secretName: secret
                - values:
                    SOCIAL_AUTH_COGNITO_POOL_DOMAIN: https://<domain>.<region>.amazoncognito.com/
                    SOCIAL_AUTH_PIPELINE:
                      [
                        "social_core.pipeline.social_auth.social_details",
                        "social_core.pipeline.social_auth.social_uid",
                        "social_core.pipeline.social_auth.auth_allowed",
                        "social_core.pipeline.social_auth.social_user",
                        "social_core.pipeline.social_auth.associate_by_email",
                        "social_core.pipeline.user.create_user",
                        "social_core.pipeline.social_auth.associate_user",
                        "social_core.pipeline.social_auth.load_extra_data",
                        "social_core.pipeline.user.user_details"
                      ]

              extraVolumes:
                - name: sso-pipeline-roles
                  configMap:
                    name: sso-pipeline-roles

              extraVolumeMounts:
                - name: sso-pipeline-roles
                  mountPath: /opt/netbox/netbox/netbox/sso_pipeline_roles.py
                  subPath: sso_pipeline_roles.py
                  readOnly: true
```
> The parameters SOCIAL_AUTH_COGNITO_KEY and SOCIAL_AUTH_COGNITO_SECRET are defined in the secret.

The configmap is declared through another file.

The issue is that I can't see the SSO login button appearing on my login page. Seems like NetBox is not seeing the SSO directives. I also can't see any SSO related variable in the pod environment, when I exec the env command in it.

I don't see any error in the pod logs that can be related to the SSO.

Also, I'm wondering wat the callbacks URL for longin et logout are, while using Cognito. I know that for Okta it's something like 
```
https://netbox.example.com/oauth/login/okta-oauth/
https://netbox.example.com/oauth/logout/okta-oauth/
```
but when I try to use them as it or adapted to fit Cognito my webpage displays an unknown request/page status.

Thanks for your help ! :)

**Comment by bootc** [comment]
I'm afraid that you've been following the README for an unreleased version of the chart. This part of your values file:
```yaml
                backends:
                  - social_core.backends.cognito.CognitoOAuth2
```
Should look like this in current released versions of the chart:
```yaml
                backend: social_core.backends.cognito.CognitoOAuth2
```
Please see the [README for 4.1.1](https://github.com/bootc/netbox-chart/blob/4.1.1/README.md), for example.

**Comment by Analepse129** [comment]
My bad, thanks for pointing that out. 

Works nicely now. 

Thanks ! :D
