### ISSUE TITLE
ARM64 compatible?

### ISSUE THREAD

**Issue by darvad** [bootc/netbox-chart#26]
Hi All,
I am new to to helm and kubernetes. Please forgive if I have overseen something obvious in the documentation. Trying to get netbox  to run on ARM64 based kubernetes cluster. Is this version of image compatible with this platform? I am not able to make it work. The pods keep crashing.

netbox-8677cc54c8-bm9jw                   0/2     CrashLoopBackOff   3          103s
netbox-postgresql-0                              0/1     CrashLoopBackOff   1          103s
netbox-redis-master-0                          0/1     CrashLoopBackOff   4          103s
netbox-redis-slave-0                             0/1     CrashLoopBackOff   3          103s

The netbox pod gets following error
$ kubectl logs netbox-8677cc54c8-bm9jw -c netbox
standard_init_linux.go:211: exec user process caused "exec format error"

Thanks ahead for any hint.
Cheers

**Comment by bootc** [comment]
The chart itself is architecture agnostic, but the image it uses (netboxcommunity/netbox)[https://hub.docker.com/r/netboxcommunity/netbox] is amd64-only. I recommend you create an issue there to get arm64 support.
