### ISSUE TITLE
Update to netbox 2.10.x

### ISSUE THREAD

**Issue by tiger-jmw** [bootc/netbox-chart#29]
Please update the chart to cater for netbox 2.10 series
https://github.com/netbox-community/netbox/releases

**Comment by stv0g** [comment]
I would suggest to pin the netbox image to a specific tag rather than using the latest. Its only causing issues

**Comment by bootc** [comment]
This will be fixed with version 3.0.0 of the chart, which I'm currently working on in `master`. The fix for this particular issue is in https://github.com/bootc/netbox-chart/commit/38f4b943abdc353d1e8d13a83c98c1b03c2601db.
