### ISSUE TITLE
(External)Database should allow TLS

### ISSUE THREAD

**Issue by sdktr** [bootc/netbox-chart#3]
Let add the option of having SSL: Require to the external database/postgres config; it provides a sane default when accessing an external DB

**Comment by bootc** [comment]
I'm really sorry, GitHub has been failing to notify me of issues and PRs on my own repo so I've only just seen this. Thanks for your contribution! It might take me a few days to get enough time to review everything and react to things, but I'll get to it all ASAP.

**Comment by bootc** [comment]
This is now available since chart version 2.0.0. You can set this with [`externalDatabase.sslMode`](https://github.com/bootc/netbox-chart/blob/2.0.0/values.yaml#L186) which currently defaults to `prefer` (following upstream's default).
