### ISSUE TITLE
Passing --values values.yaml results in django.db.utils.OperationalError: FATAL:  password authentication failed for user "netbox"

### ISSUE THREAD

**Issue by adamwoolhether** [bootc/netbox-chart#38]
I've tried a number of different scenarios passing values with the values.yaml file, all result in this error, viewed with kubectl logs....

Even leaving the values at default, and running `helm install netbox-test --values values.yaml --set postgresqlPostgresqlPostgresPassword=password1 --set postgresql.postgresqlPassword=password2 bootc/netbox` results in failure. Same thing without passing the `--set` flags.

The only way to customized the helm install is manually typing each parameter with the '--set' flag.

**Comment by adamwoolhether** [comment]
I'm sorry, I wasn't taking into account the Persistent Volume Claims. I cleared those before making further changes and this allowed me to solve the issue.

**Comment by bootc** [comment]
Ah brill, thanks for the update and glad you got it going!
