### ISSUE TITLE
Error with Postgreslq image

### ISSUE THREAD

**Issue by marcoapvilhena** [bootc/netbox-chart#40]
I'm trying install de Netbox, but the netbox-postgresql-0 pod is ImagePullBackOff status.

Describing the pod we got the message:

Warning  Failed     61s                  kubelet, docker-desktop  Failed to pull image "docker.io/bitnami/postgresql:11.11.0-debian-10-r0": rpc error: code = Unknown desc = context canceled
  Warning  Failed     61s                  kubelet, docker-desktop  Error: ErrImagePull
  Normal   BackOff    60s                  kubelet, docker-desktop  Back-off pulling image "docker.io/bitnami/postgresql:11.11.0-debian-10-r0"

has anyone faced it?

**Comment by bootc** [comment]
This definitely looks like an issue on your end I'm afraid. The bundled PostgreSQL chart is just the bog-standard Bitnami PostgreSQL chart, and the image is its default image. It downloads and works fine for me:

```console
$ docker puldocker.io/bitnami/postgresql:11.11.0-debian-10-r0r0
11.11.0-debian-10-r0: Pulling from bitnami/postgresql
d3719229d1dc: Pull complete 
061963e25074: Pull complete 
79b2bc580100: Pull complete 
9c2c1b69db14: Pull complete 
3634b1943670: Pull complete 
f74469b0184e: Pull complete 
72d505dea92a: Pull complete 
e35ccb1d7c40: Pull complete 
6afbd3d66b8a: Pull complete 
09d1050d2231: Pull complete 
0f57bf8a09b6: Pull complete 
94801318f55f: Pull complete 
c627fff63a34: Pull complete 
Digest: sha256:a0c2f337313d968d9ca6115f56ee49161d794f6cce4dd7a270c15b26c7febbe9
Status: Downloaded newer image for bitnami/postgresql:11.11.0-debian-10-r0
docker.io/bitnami/postgresql:11.11.0-debian-10-r0
```
