### ISSUE TITLE
Sealed Secret for option for LDAP + netbox built-in admin

### ISSUE THREAD

**Issue by florianschendel** [bootc/netbox-chart#42]
Hello,

is there a special reason why the LDAP env variables were changed to a LDAP YAML file? With this implementation its not longer possible to use a Sealed Secrets to put a predefined LDAP sealed secret during a helm install + vales.yaml.
Same topic for the netbox built-in admin, its only possible to put the password or api-string as clear text password in the yaml file.

I´m not really a helm specialist maybe there is a easy way to forward a sealed secret into my helm deployment without changing the template? Otherwise it would be a feature request ;)

**Comment by bootc** [comment]
You can set `existingSecret` to `true` and the `Secret` resource will not be created, so it's up to you to supply it. This can contain all the passwords you need, including the `ldap_bind_password`.
