### ISSUE TITLE
Update chart for 2.11.2

### ISSUE THREAD

**Issue by bluecmd** [bootc/netbox-chart#45]
Hi,

It seems these charts are running on the older 2.10.x train, but 2.11.2 was just now released.

It would be nice if these charts were updated to run the latest, or at least something on the 2.11 train.

**Comment by bootc** [comment]
Yep, I was waiting for the container images to become available to see how much needed doing. I'm planning to take a look at this as soon as I can.

**Comment by bootc** [comment]
I still plan to update the chart, but no significant changes are required to support v2.11 so it's perfectly safe to just use the newer Docker image with the current version of the chart. I have just tested this.

**Comment by bootc** [comment]
We're now planning an update for NetBox 3.x so I'll close this issue in favour of #65
