### ISSUE TITLE
How set ingress.hosts value with command line?

### ISSUE THREAD

**Issue by sasho4ek07** [bootc/netbox-chart#50]
I try set ingress.hosts so:
`helm install netbox bootc/netbox --set postgresql.postgresqlPostgresPassword=[password1] --set postgresql.postgresqlPassword=[password2] --set ingress.enabled=true --set ingress.hosts=[{host:"chart-example.local",paths:["/"]}]` but get
but I get the error:
`expected at most two arguments, unexpected arguments: ingress.hosts=[paths:[/]]`
I also tried:
`--set ingress.hosts="[{host:"chart-example.local", paths:["/"]}]"` -> `Error: failed parsing --set data: error parsing index: strconv.Atoi: parsing "/": invalid syntax`
I just recently started to study helm and am trying to figure out how to solve the problem, please tell me the correct solution?

**Comment by bootc** [comment]
This is more a question about how Helm does this rather than this chart. Personally I just use a `values.yaml` file and use `--values values.yaml` (actually, I use [Flux](https://fluxcd.io)'s Helm Controller).

If you really want to do this on the command-line, though, I believe the syntax is:
```
[...]
--set ingress.hosts[0].host=chart-example.local \
--set ingress.hosts[0].paths[0]=/ \
[...]
```
