### ISSUE TITLE
Worker HPA broken

### ISSUE THREAD

**Issue by jweiher** [bootc/netbox-chart#51]
Hi,

I tried to use the worker hpa but it fails because of an undefined template:
```netbox/templates/worker-hpa.yaml:7:8: executing \"netbox/templates/worker-hpa.yaml\" at <include \"netbox.worker.labels\" .>: error calling include: template: no template \"netbox.worker.labels\" associated with template \"gotpl\"\n"```
I'm not that familiar with helm but from my perspective the fix might just be changing the netbox.worker.labels to netbox.labels in worker-hpa.yaml?

kind regards,
Jan

**Comment by bootc** [comment]
This is easy enough to fix, but come to think of it is there a valid use case for running more than one worker instance? Would it be more correct to remove the HPA and restrict the worker Deployment to only 1 replica?

**Comment by bootc** [comment]
I've just released version [4.0.1](https://github.com/bootc/netbox-chart/releases/tag/4.0.1) of this chart which resolves this issue.
