### ISSUE TITLE
Worker missing worker specific environment variables

### ISSUE THREAD

**Issue by jeremypng** [bootc/netbox-chart#53]
Line 55 of netbox-chart/templates/worker-deployment.yaml only grabs the global extraEnvs and not the ones under the worker key.

**Comment by bootc** [comment]
You're right, and there's a similar issue with `extraVolumes` as well. I'm queuing up a fix for this.

**Comment by bootc** [comment]
I've just released version [4.0.1](https://github.com/bootc/netbox-chart/releases/tag/4.0.1) of this chart which resolves this issue.
