### ISSUE TITLE
version label not set properly

### ISSUE THREAD

**Issue by dimitrigraf** [bootc/netbox-chart#57]
This is a rather cosmetic one but might still be important and should be easy to fix I guess:

When using a different netbox version than the one specified in the `Chart.yaml` by setting `image.tag`, the version label `app.kubernetes.io/version` is not set properly.

I guess that's due to the label being set like this: `templates/_helpers.tpl:app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}` 

I'm not really experienced with go templates but maybe it should be sth like the following:
`{{ .Values.image.tag | default .Chart.AppVersion | quote }}`

**Comment by bootc** [comment]
I've just released version [4.0.1](https://github.com/bootc/netbox-chart/releases/tag/4.0.1) of this chart which resolves this issue.
