### ISSUE TITLE
LDAP support is missing in helm chart

### ISSUE THREAD

**Issue by Comradin** [bootc/netbox-chart#6]
Hello,

The current release (1.0.4) of the helm chart does not support ldap authentication.

Please add this feature.

**Comment by c-po** [comment]
It feels that recent versions of this chart support passing in the values via environment variables.

https://github.com/bootc/netbox-chart/blob/master/values.yaml#L446-L452

**Comment by bootc** [comment]
This is implemented in #31 and will be in the 3.0.0 release of the chart which I plan to release this week.
