### ISSUE TITLE
Update chart for v3

### ISSUE THREAD

**Issue by N3v3R3nD** [bootc/netbox-chart#65]
Hello, 

Is it possible to update the helm chart for the v3?

**Comment by rjhenry** [comment]
I know Chris is working on this one, but I don't know how much time he's able to allocate to it. Are there any tasks that we can contribute to this with, Chris?

**Comment by bootc** [comment]
Hey @rjhenry, as you've gathered I currently have no real time I can dedicate to maintaining this. I've pushed what work I've done so far to the `develop` branch but clearly lots more needs doing. If there's something you (or anyone else) would like to work on, please update the relevant issue to avoid duplicating work - and I vow to at least review PRs as they come in.

I think this chart is going to need a 4.0 revision for NetBox 3.x, realistically, so I'd like to get as many breaking changes out of the way as possible with that update.

**Comment by jfelten** [comment]
@bootc This is a well done chart and it would be a shame not to update it. FYI I bumped appVersion in the develop branch to:
```
appVersion: v3.0.10
```
and it installed/started with no issues with a fresh db on k8s v1.21 and default config. There is apparently some upgrade trickiness with updating the db for exiting installs. Nextbox first needs to be updated to >2.10- <2.11 first before updating to 3. That should be called out.

What is in the develop branch seems pretty good. Was there something else you wanted to redo/test? Happy to put up a draft PR if you are too busy.

**Comment by rjhenry** [comment]
For Netbox v3+, the largest thing needed is likely the [Housekeeping task](https://demo.netbox.dev/static/docs/administration/housekeeping/); I've got a fork with which I'm working on getting that set up as a Kubernetes CronJob with sensible options.

**Comment by bootc** [comment]
@jfelten exactly what @rjhenry says, we need the housekeeping task adding in. A CronJob sounds perfect for this Rick, thanks for looking at it.

**Comment by rjhenry** [comment]
I've got a PR now pending for the housekeeping task, and all I can see that needs to be done before cutting the 4.0 chart release is a slight cleanup of the configmap (CACHE_TIMEOUT and RELEASE_CHECK_TIMEOUT no longer do anything for v3.+). Would you agree @bootc ?

**Comment by bootc** [comment]
Hey @rjhenry thanks for that, that's now merged.

I had wanted to refactor how the config and especially the secrets are templated as it currently isn't very flexible, for issue #56. It would be nice to be able to feed arbitrary secrets and extra config in so people can push in whatever values they need, such as for the object storage in that issue, or plugins, or newer versions of NetBox. Do you have any thoughts about how that might work?

Otherwise we can probably just cut 4.x soon and do that for a future release?

**Comment by jfelten** [comment]
@bootc @rjhenry - Sounds good to me and thank you! 2 PRs: 1. push the develop branch with latest netbox release with migrations instructions. 2. Housekeeping cronjob. I'd offer to help with media storage credentials the I don't use a cloud provider, and have no good way to test it. If there is something else I can do to help let me know.

**Comment by rjhenry** [comment]
Personally, I'd suggest cutting 4.0 soon and working on better extra config at a later date; that allows places using this chart to jump to NetBox 3.0 for extra niceness.

**Comment by bootc** [comment]
I've pushed a few more updates to the `develop` branch, including actually updating to NetBox 3.0.11. We're getting closer now, but not quite there yet.

**Comment by bootc** [comment]
So I've had a bit of a poke around and created a milestone to track what's left to do for 4.0. As of now there are two remaining issues I'd like to include: https://github.com/bootc/netbox-chart/issues?q=is%3Aopen+milestone%3A4.0+-label%3Apending

**Comment by bootc** [comment]
Right I've got those two issues sorted out now. I'd really appreciate some testing and review of the current state of the `develop` branch if anyone wouldn't mind. With some review and testing we can get the chart released pretty soon I should think.

**Comment by rjhenry** [comment]
Working just fine here, deploying with no issues. Will let the CronJob run overnight and make sure that all looks good, but everything appears to be behaving as far as I can tell.

**Comment by bootc** [comment]
I've just released version [4.0.1](https://github.com/bootc/netbox-chart/releases/tag/4.0.1) of this chart which resolves this issue.
