### ISSUE TITLE
NodePort is missing in templates/service.yaml

### ISSUE THREAD

**Issue by clyso-dr** [bootc/netbox-chart#69]
I tried to set the NodePort and always get a random nodeport because in the service.yaml is missing something like this:

`nodePort: {{ .Values.service.nodePort }}`

@bootc I would appreciate if you can add this, thanks!

**Comment by clyso-dr** [comment]
Are there a rough timeline to fix this bug?

**Comment by bootc** [comment]
I'm going to try to fix it over the next few days.

**Comment by bootc** [comment]
This is fixed in the `develop` branch with https://github.com/bootc/netbox-chart/commit/8382eeae3fbe47d0888276b4fc69d5dbe3bcfadc but I forgot to tag the commit message.

**Comment by clyso-dr** [comment]
Ok thank you, i will check out the develop branch for a test install.

**Comment by clyso-dr** [comment]
`Helm install failed: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service.spec.ports[0].nodePort): invalid type for io.k8s.api.core.v1.ServicePort.nodePort: got "string", expected "integer"`

Maybe the "| quote"?

**Comment by bootc** [comment]
D'oh I wasn't thinking straight, of course the port number can't be quoted. I've just pushed a fix.

**Comment by clyso-dr** [comment]
Thanks, now its working! Should I close the bug or leave it open until tagging?

**Comment by bootc** [comment]
Let's leave this open until I tag an updated chart, thanks.

**Comment by bootc** [comment]
This is included in chart version 4.1.0.
