### ISSUE TITLE
Add support for loadBalancerSourceRanges in k8s service

### ISSUE THREAD

**Issue by eversC** [bootc/netbox-chart#8]
I'd like to be able to set the IP ranges that are allowed to access my netbox k8s service (I'm using type: LoadBalancer).

This is possible using `loadBalancerSourceRanges` (see https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service)

Please add support for `loadBalancerSourceRanges`.

**Comment by bootc** [comment]
I'm really sorry, GitHub has been failing to notify me of issues and PRs on my own repo so I've only just seen this. Thanks for your contribution! It might take me a few days to get enough time to review everything and react to things, but I'll get to it all ASAP.

**Comment by bootc** [comment]
This is included in version 2.0.1 of the chart, which includes an update to NetBox 2.7.7.
