### ISSUE TITLE
dependency on Bitnami causes the helm to be only compatible with AMD64 architecture

### ISSUE THREAD

**Issue by anubisg1** [bootc/netbox-chart#85]
as per title, we have a dependency on postgres and redis but they are pulled from bitnami.
Both are provided by bitnami as pure amd64 images.

official redis and postgress do support multiple architectures , including among others arm64 

An effort should be made to migrate to an arch agnostic deployment

**Comment by bootc** [comment]
As I've mentioned here:
https://github.com/bootc/netbox-chart/tree/develop#production-usage

For production use I advise against using the bundled charts for Redis or PostgreSQL. You should ideally run your own instances of those, and you can choose to run whatever you like from anywhere you like.

This particular text isn't on the `master` branch yet so I'm not surprised if you haven't seen it. Also NetBox itself doesn't run on anything but `amd64` at the moment, though I know there is an effort to make it run on other architectures.
